language: bash
sudo: required

install:
  - docker pull dapperstats/accessor
  - docker run --name acc -t dapperstats/accessor
  - docker cp acc:/data .

script:
  - ls data

after_success:
  - ls data