# accessor docker
name: docker

on:
  pull_request:
    branches:
      - master



jobs:
  build:
    name: container build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build image
        run: |
          docker build . --file Dockerfile -t dapperstats/accessor:gha . 

